/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import dominio.Puesto;
import dominio.Tarifa;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.controladores.ControladorEmularTransito;
import ui.interfaces.EmularTransitoVista;

/**
 *
 * @author usuario
 */
public class DialogoEmularTransito extends javax.swing.JDialog implements EmularTransitoVista {

    private ControladorEmularTransito controlador;
    private DefaultTableModel modelTablaTarifas = tablaTarifas();

    /**
     * Creates new form DialogoEmularTransito
     */
    public DialogoEmularTransito() {
        this.controlador = new ControladorEmularTransito(this);
        initComponents();
        this.inicializar();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPuestos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTarifa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbPuestos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPuestosItemStateChanged(evt);
            }
        });
        cbPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPuestosActionPerformed(evt);
            }
        });
        cbPuestos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbPuestosPropertyChange(evt);
            }
        });
        cbPuestos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbPuestosKeyPressed(evt);
            }
        });

        jLabel1.setText("Puestos:");

        jLabel2.setText("Tarifas:");

        tTarifa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tTarifa);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel3.setText("Ingrese matricula:");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(453, 453, 453))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtMatricula)
                            .addGap(578, 578, 578))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(500, 500, 500)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(jLabel3)
                    .addComponent(txtMatricula))
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPuestosActionPerformed

    }//GEN-LAST:event_cbPuestosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
      this.registrarTransito();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbPuestosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbPuestosKeyPressed

    }//GEN-LAST:event_cbPuestosKeyPressed

    private void cbPuestosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPuestosItemStateChanged
          int stateChange = evt.getStateChange();
            if (stateChange == ItemEvent.SELECTED) {
                    String nombrePuesto =  cbPuestos.getSelectedItem().toString();;
                    controlador.mostrarTarifas(nombrePuesto);
            }
    }//GEN-LAST:event_cbPuestosItemStateChanged

    private void cbPuestosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbPuestosPropertyChange

    }//GEN-LAST:event_cbPuestosPropertyChange

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed

    }//GEN-LAST:event_txtMatriculaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbPuestos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tTarifa;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables

    public void inicializar(){
        this.controlador.mostrarPuestos();
        tTarifa.setModel(modelTablaTarifas);
    }
    
    @Override
    public void mostrarEmuladorTransito() {
    }

    @Override
    public void mostrarTarifas(Puesto puesto) {
       ArrayList<Tarifa> tarifas = puesto.getTarifas();
        if (tarifas != null) {

            for (Tarifa t : tarifas) {
                modelTablaTarifas.addRow(new Object[]{t.getCategoriaVehiculo().getNombre() , t.getMonto()});
            }
        } 
    }

    @Override
    public void registrarTransito()  {
        controlador.registrarTransito(txtMatricula.getText());         
    }

    @Override
    public void cerrar() {
    dispose();
    }

    @Override
    public void mostrarMensajeDeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarPuestos(ArrayList<Puesto> puestos) {
              for (Puesto p : puestos) {
            cbPuestos.addItem(p.getNombre());
        }
    }
 
    
        public DefaultTableModel tablaTarifas() {
        return new DefaultTableModel(
                new String[]{
                    "Categoria", "Monto"
                }, 0
        );
    }

}
