/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.interfaces.MenuAdministradorVista;
import dominio.Administrador;
import dominio.Usuario;
import ui.controladores.ControladorMenuAdministrador;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class DialogoMenuAdministrador extends javax.swing.JDialog implements MenuAdministradorVista {

    /**
     * Creates new form DialogoMenuAdministrador
     */
    private ControladorMenuAdministrador controlador;

    public DialogoMenuAdministrador(Administrador administrador) {
        this.controlador = new ControladorMenuAdministrador(administrador, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        EmularTransito = new javax.swing.JMenu();
        emularTransito = new javax.swing.JMenuItem();
        emularAprobacionRecarga = new javax.swing.JMenuItem();
        asignarBonificacion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EmularTransito.setText("File");

        emularTransito.setText("Emular Transito");
        emularTransito.setName("emularTransito"); // NOI18N
        emularTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emularTransitoActionPerformed(evt);
            }
        });
        EmularTransito.add(emularTransito);

        emularAprobacionRecarga.setText("Emular aprobacion de recarga");
        emularAprobacionRecarga.setName("emularAprobacionRecarga"); // NOI18N
        emularAprobacionRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emularAprobacionRecargaActionPerformed(evt);
            }
        });
        EmularTransito.add(emularAprobacionRecarga);

        asignarBonificacion.setText("Asignar bonificacion");
        asignarBonificacion.setName("asignarBonificacion"); // NOI18N
        asignarBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarBonificacionActionPerformed(evt);
            }
        });
        EmularTransito.add(asignarBonificacion);

        salir.setText("Salir");
        salir.setName("salir"); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        EmularTransito.add(salir);

        jMenuBar1.add(EmularTransito);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emularTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emularTransitoActionPerformed
        navegar(emularTransito.getName());
    }//GEN-LAST:event_emularTransitoActionPerformed

    private void emularAprobacionRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emularAprobacionRecargaActionPerformed
        navegar(emularAprobacionRecarga.getName());
    }//GEN-LAST:event_emularAprobacionRecargaActionPerformed

    private void asignarBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarBonificacionActionPerformed
        navegar(asignarBonificacion.getName());
    }//GEN-LAST:event_asignarBonificacionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        navegar(salir.getName());
    }//GEN-LAST:event_salirActionPerformed

    @Override
    public void navegar(String opcion) {
        Administrador admin = this.controlador.getAdministrador();
        switch (opcion) {
            case "emularTransito":
                new DialogoEmularTransito();
                break;
            case "emularAprobacionRecarga":
                new DialogoEmularAprobacionRecarga(admin).setVisible(true);
                break;
            case "asignarBonificacion":
                new DialogoAsignarBonificaciones().setVisible(true);
                break;
            case "salir":
                dispose();
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EmularTransito;
    private javax.swing.JMenuItem asignarBonificacion;
    private javax.swing.JMenuItem emularAprobacionRecarga;
    private javax.swing.JMenuItem emularTransito;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
