/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import ui.interfaces.TableroPropietarioVista;
import dominio.Asignacion;
import dominio.Bonificacion;
import dominio.Notificacion;
import dominio.Propietario;
import dominio.RecargaSaldo;
import dominio.Transito;
import dominio.Usuario;
import dominio.Vehiculo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import ui.controladores.ControladorTableroPropietario;

/**
 *
 * @author usuario
 */
public class DialogoTableroPropietario extends javax.swing.JFrame implements TableroPropietarioVista {

    private ControladorTableroPropietario controlador;

    /**
     * Creates new form DialogoTableroPropietario
     */
    public DialogoTableroPropietario(Propietario propietario) {
        initComponents();
        this.controlador = new ControladorTableroPropietario(this, propietario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPropietario = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblVehiculosCantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        lblBonificacionesCantidad = new javax.swing.JLabel();
        lblTransitosCantidad = new javax.swing.JLabel();
        lblNotificacionesCantidad = new javax.swing.JLabel();
        lblRecargasCantidad = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tTransitos = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tBonificaciones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tRecargas = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tNotificaciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRecargar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblPropietario.setText("varPropietario");

        lblSaldo.setText("varSaldo");

        lblVehiculosCantidad.setText("CantidadVehiculos");

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Modelo", "Color", "#Transitos", "Monto total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        jScrollPane2.setViewportView(jScrollPane1);

        lblBonificacionesCantidad.setText("CantidadBonificaciones");

        lblTransitosCantidad.setText("CantidadTransitos");

        lblNotificacionesCantidad.setText("CantidadNotificaciones");

        lblRecargasCantidad.setText("CantidadRecargas");

        tTransitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Puesto", "Matricula", "Tarifa", "Tarifa(Monot)", "Bonificacion", "Bonific.(Monot)", "Monto pagado", "Fecha"
            }
        ));
        jScrollPane4.setViewportView(tTransitos);

        jScrollPane8.setViewportView(jScrollPane4);

        tBonificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Bonificacion", "Puesto", "Fecha Asignada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tBonificaciones);

        jScrollPane11.setViewportView(jScrollPane6);

        tRecargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha recarga", "Monto", "Estado", "Administrador"
            }
        ));
        jScrollPane7.setViewportView(tRecargas);

        jScrollPane3.setViewportView(jScrollPane7);

        tNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Mensaje"
            }
        ));
        jScrollPane5.setViewportView(tNotificaciones);

        jScrollPane12.setViewportView(jScrollPane5);

        jLabel2.setText("Bonificaciones");

        jLabel3.setText("Transitos");

        jLabel4.setText("Recargas de saldo");

        jLabel5.setText("Notificaciones");
        jLabel5.setToolTipText("");

        jLabel6.setText("Vehiculos");

        jLabel7.setText("Propietario:");

        jLabel8.setText("Dinero");

        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCerrar.setText("cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblPropietario)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehiculosCantidad)
                            .addComponent(lblBonificacionesCantidad)
                            .addComponent(lblTransitosCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNotificacionesCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(lblRecargasCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRecargar)
                                    .addComponent(btnBorrar))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(btnCerrar)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(lblSaldo)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehiculosCantidad)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBonificacionesCantidad)
                            .addComponent(jLabel2))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransitosCantidad)
                            .addComponent(jLabel3))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecargasCantidad)
                            .addComponent(jLabel4)
                            .addComponent(btnRecargar))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNotificacionesCantidad)
                            .addComponent(jLabel5)
                            .addComponent(btnBorrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(btnCerrar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        controlador.borrarNotificacion();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        controlador.recargaSaldo();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        controlador.cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controlador.cerrar();
    }//GEN-LAST:event_formWindowClosed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblBonificacionesCantidad;
    private javax.swing.JLabel lblNotificacionesCantidad;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblRecargasCantidad;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTransitosCantidad;
    private javax.swing.JLabel lblVehiculosCantidad;
    private javax.swing.JTable tBonificaciones;
    private javax.swing.JTable tNotificaciones;
    private javax.swing.JTable tRecargas;
    private javax.swing.JTable tTransitos;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTablero(Propietario propietario) {
        this.mostrarNombreCompleto(propietario.getNombreCompleto());
        this.mostrarSaldo(Float.toString(propietario.getSaldo()));
        this.mostrarVehiculos(propietario.getVehiculos());
        this.mostrarBonificaciones(propietario.getAsignaciones());
    }

    @Override
    public void mostrarNombreCompleto(String nombreCompleto) {
        lblPropietario.setText(nombreCompleto);
    }

    @Override
    public void mostrarSaldo(String monto) {
        lblSaldo.setText(monto);
    }

    @Override
    public void mostrarVehiculos(ArrayList<Vehiculo> vehiculos) {
        lblVehiculosCantidad.setText(Integer.toString(vehiculos.size()));
        if (vehiculos.size() != 0) {
            DefaultTableModel model = tablaVehiculos();
            tablaVehiculos.setModel(model);
            for (Vehiculo v : vehiculos) {
                model.addRow(new Object[]{v.getMatricula(), v.getModelo(), v.getColor(), v.getTransitos().size(), v.getMontoTotal()});
            }
        }
    }

    @Override
    public void mostrarBonificaciones(ArrayList<Asignacion> asignaciones) {
        lblBonificacionesCantidad.setText(Integer.toString(asignaciones.size()));
        if (asignaciones.size() != 0) {
            DefaultTableModel model = tablaBonificaciones();
            tBonificaciones.setModel(model);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            for (Asignacion a : asignaciones) {
                model.addRow(new Object[]{a.getBonificacion().getNombre(), a.getPuesto().getNombre(), formato.format(a.getFecha())});
            }
        }
    }

    @Override
    public void mostrarTransitos(ArrayList<Transito> transitos) {
        lblTransitosCantidad.setText(Integer.toString(transitos.size()));
        if (transitos.size() != 0) {
            DefaultTableModel model = tablaTransitos();
            tTransitos.setModel(model);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            for (Transito t : transitos) {
                model.addRow(new Object[]{t.getPuesto().getNombre(), t.getVehiculo().getMatricula(), t.getTarifa().getNombre(), t.getTarifa().getMonto(), t.getTotal(), formato.format(t.getFecha())});
            }
        }
    }

    @Override
    public void mostrarRecargas(ArrayList<RecargaSaldo> recargas) {
        lblRecargasCantidad.setText(Integer.toString(recargas.size()));
        if (recargas.size() != 0) {
            DefaultTableModel model = tablaRecargas();
            tRecargas.setModel(model);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            for (RecargaSaldo rs : recargas) {
                String nombreAdmin = rs.getAdministrador() != null ? rs.getAdministrador().getNombreCompleto() : "No tiene administrador";
                String aprobado = rs.isEstado() ? "Aprobado" : "Pendiente";
                model.addRow(new Object[]{formato.format(rs.getFechaInicio()), rs.getMonto(), aprobado, nombreAdmin});
            }
        }
    }

    @Override
    public void mostrarNotificacion(ArrayList<Notificacion> notificaciones) {
        lblNotificacionesCantidad.setText(Integer.toString(notificaciones.size()));
        if (notificaciones.size() != 0) {
            {
                DefaultTableModel model = tablaNotificaciones();
                tNotificaciones.setModel(model);
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                for (Notificacion n : notificaciones) {
                    model.addRow(new Object[]{formato.format(n.getFecha()), n.getMensaje()});
                }
            }

        }
    }

    @Override
    public void borrarNotificaciones(Propietario propietario) {
    }

    @Override
    public void recargaSaldo(Propietario propietario) {
        new DialogoRecargaSaldo(this, false, propietario).setVisible(true);
    }

    @Override
    public void cerrar() {
        dispose();
    }

    public DefaultTableModel tablaVehiculos() {
        return new DefaultTableModel(
                new String[]{
                    "Matricula", "Modelo", "Color", "#Transitos", "Monto total"
                }, 0
        );
    }

    public DefaultTableModel tablaBonificaciones() {
        return new DefaultTableModel(
                new String[]{
                    "Nombre bonificación", "Puesto", "Fecha asignada"
                }, 0
        );
    }

    public DefaultTableModel tablaTransitos() {
        return new DefaultTableModel(
                new String[]{
                    "Puesto", "Matricula", "Tarifa", "Tarifa(monto)", "Bonific,", "Bonific.(monto)", "Monto pagado", "Fecha"
                }, 0
        );
    }

    public DefaultTableModel tablaRecargas() {
        return new DefaultTableModel(
                new String[]{
                    "Fecha recarga", "Monto", "Estado", "Administrador"
                }, 0
        );
    }

    public DefaultTableModel tablaNotificaciones() {
        return new DefaultTableModel(
                new String[]{
                    "Fecha", "Mensaje"
                }, 0
        );
    }
}
