/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.interfaces.MenuAdministradorVista;
import dominio.Administrador;
import dominio.Usuario;
import ui.controladores.ControladorMenuAdministrador;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class DialogoMenuAdministrador extends javax.swing.JFrame implements MenuAdministradorVista {

    /**
     * Creates new form DialogoMenuAdministrador
     */
    private ControladorMenuAdministrador controlador;

    public DialogoMenuAdministrador(Administrador administrador) {
        this.controlador = new ControladorMenuAdministrador(administrador, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        EmularTransito = new javax.swing.JMenu();
        emularTransito = new javax.swing.JMenuItem();
        emularAprobacionRecarga = new javax.swing.JMenuItem();
        asignarBonificacion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu del administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        EmularTransito.setText("Menu");

        emularTransito.setText("Emular Transito");
        emularTransito.setName("emularTransito"); // NOI18N
        emularTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emularTransitoActionPerformed(evt);
            }
        });
        EmularTransito.add(emularTransito);

        emularAprobacionRecarga.setText("Emular aprobacion de recarga");
        emularAprobacionRecarga.setName("emularAprobacionRecarga"); // NOI18N
        emularAprobacionRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emularAprobacionRecargaActionPerformed(evt);
            }
        });
        EmularTransito.add(emularAprobacionRecarga);

        asignarBonificacion.setText("Asignar bonificacion");
        asignarBonificacion.setName("asignarBonificacion"); // NOI18N
        asignarBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarBonificacionActionPerformed(evt);
            }
        });
        EmularTransito.add(asignarBonificacion);

        salir.setText("Salir");
        salir.setName("salir"); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        EmularTransito.add(salir);

        jMenuBar1.add(EmularTransito);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emularTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emularTransitoActionPerformed
        this.controlador.navegar(emularTransito.getName());
    }//GEN-LAST:event_emularTransitoActionPerformed

    private void emularAprobacionRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emularAprobacionRecargaActionPerformed
        this.controlador.navegar(emularAprobacionRecarga.getName());
    }//GEN-LAST:event_emularAprobacionRecargaActionPerformed

    private void asignarBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarBonificacionActionPerformed
        this.controlador.navegar(asignarBonificacion.getName());
    }//GEN-LAST:event_asignarBonificacionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.controlador.navegar(salir.getName());
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.controlador.navegar(salir.getName());
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EmularTransito;
    private javax.swing.JMenuItem asignarBonificacion;
    private javax.swing.JMenuItem emularAprobacionRecarga;
    private javax.swing.JMenuItem emularTransito;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarDialogoEmularTransito() {
        //new DialogoEmularTransito().setVisible(true);
    }

    @Override
    public void mostrarDialogoEmularAprobacionRecarga(Administrador administrador) {
        new DialogoEmularAprobacionRecarga(administrador).setVisible(true);
    }

    @Override
    public void mostrarDialogoAsignarBonificaciones() {
        new DialogoAsignarBonificaciones().setVisible(true);
    }

    @Override
    public void salir() {
        dispose();
    }
    
    
}
